botocore.credentials - INFO - Found credentials from IAM Role: GPUInstance1
__main__ - ERROR - 
Error loading components: Traceback (most recent call last):
  File "/home/ubuntu/intern-project-LLM-RAG/src/streamlit_whiterabbit_redteam.py", line 610, in <module>
    delete_files('S3InputBucket-Redteam', DATA_PATH)
  File "/home/ubuntu/intern-project-LLM-RAG/src/streamlit_whiterabbit_redteam.py", line 451, in delete_files
    shutil.rmtree(local_folder)
  File "/home/ubuntu/anaconda3/lib/python3.12/shutil.py", line 759, in rmtree
    _rmtree_safe_fd(stack, onexc)
  File "/home/ubuntu/anaconda3/lib/python3.12/shutil.py", line 703, in _rmtree_safe_fd
    onexc(func, path, err)
  File "/home/ubuntu/anaconda3/lib/python3.12/shutil.py", line 669, in _rmtree_safe_fd
    orig_st = os.lstat(name, dir_fd=dirfd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../cyber_data'

