botocore.credentials - INFO - Found credentials from IAM Role: GPUInstance1
__main__ - ERROR - 
Error loading components: Traceback (most recent call last):
  File "/home/ubuntu/intern-project-LLM-RAG/src/streamlit_whiterabbit_redteam.py", line 608, in <module>
    delete_files('S3InputBucket-Redteam', DATA_PATH)
  File "/home/ubuntu/intern-project-LLM-RAG/src/streamlit_whiterabbit_redteam.py", line 446, in delete_files
    bucket = s3.Bucket(bucket_name, credentials['AccessKeyId'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/lib/python3.12/site-packages/boto3/resources/factory.py", line 528, in create_resource
    return partial(
           ^^^^^^^^
  File "/home/ubuntu/anaconda3/lib/python3.12/site-packages/boto3/resources/base.py", line 107, in __init__
    setattr(self, '_' + self.meta.identifiers[i], value)
                        ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

